package deploy

import (
	"fmt"
	"net"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"codex-gateway/internal/auth"
	"codex-gateway/internal/config"
	"gopkg.in/yaml.v3"
)

type clientWrapperEndpoint struct {
	Name      string
	EnvPath   string
	LocalHost string
	LocalPort int
}

func RenderVPSEnv(spec VPSConfig) ([]byte, error) {
	usersPath := filepath.Join(spec.ProjectRoot, "config", "users.txt")
	env := map[string]string{
		"PROXY_LISTEN_ADDR":                spec.Runtime.ProxyListenAddr,
		"PROXY_LISTEN_PORT":                strconv.Itoa(spec.Runtime.ProxyListenPort),
		"ADMIN_LISTEN_ADDR":                spec.Runtime.AdminListenAddr,
		"ADMIN_LISTEN_PORT":                strconv.Itoa(spec.Runtime.AdminListenPort),
		"PROXY_TLS_ENABLED":                strconv.FormatBool(spec.Runtime.ProxyTLSEnabled),
		"PROXY_TLS_CERT_FILE":              spec.Runtime.ProxyTLSCertFile,
		"PROXY_TLS_KEY_FILE":               spec.Runtime.ProxyTLSKeyFile,
		"AUTH_USERS_FILE":                  usersPath,
		"AUTH_USERS":                       "",
		"SOURCE_ALLOWLIST_CIDRS":           strings.Join(spec.Runtime.SourceAllowlistCIDRs, ","),
		"DEST_PORT_ALLOWLIST":              joinInts(spec.Runtime.DestPortAllowlist),
		"DEST_HOST_ALLOWLIST":              strings.Join(spec.Runtime.DestHostAllowlist, ","),
		"DEST_SUFFIX_ALLOWLIST":            strings.Join(spec.Runtime.DestSuffixAllowlist, ","),
		"ALLOW_EMPTY_DEST_ALLOWLIST":       strconv.FormatBool(spec.Runtime.AllowEmptyDestAllowlist),
		"ALLOW_PRIVATE_DESTINATIONS":       strconv.FormatBool(spec.Runtime.AllowPrivateDestinations),
		"MAX_CONNS_PER_IP":                 strconv.Itoa(spec.Runtime.MaxConnsPerIP),
		"SERVER_READ_HEADER_TIMEOUT":       spec.Runtime.ServerReadHeaderTimeout,
		"SERVER_IDLE_TIMEOUT":              spec.Runtime.ServerIdleTimeout,
		"UPSTREAM_DIAL_TIMEOUT":            spec.Runtime.UpstreamDialTimeout,
		"UPSTREAM_TLS_HANDSHAKE_TIMEOUT":   spec.Runtime.UpstreamTLSHandshakeTimeout,
		"UPSTREAM_RESPONSE_HEADER_TIMEOUT": spec.Runtime.UpstreamResponseHeaderTimeout,
		"TUNNEL_IDLE_TIMEOUT":              spec.Runtime.TunnelIdleTimeout,
		"MAX_HEADER_BYTES":                 strconv.Itoa(spec.Runtime.MaxHeaderBytes),
		"LOG_LEVEL":                        spec.Runtime.LogLevel,
		"LOG_FORMAT":                       spec.Runtime.LogFormat,
		"ACCESS_LOG_ENABLED":               strconv.FormatBool(spec.Runtime.AccessLogEnabled),
		"METRICS_ENABLED":                  strconv.FormatBool(spec.Runtime.MetricsEnabled),
		"ALLOW_PUBLIC_ADMIN":               strconv.FormatBool(spec.Runtime.AllowPublicAdmin),
		"ALLOW_INSECURE_PUBLIC_PROXY":      strconv.FormatBool(spec.Runtime.AllowInsecurePublicProxy),
		"CLAUDE_OAUTH_ENABLED":             strconv.FormatBool(spec.ClaudeOAuth.Enabled),
		"CLAUDE_OAUTH_REFRESH_TOKEN":       spec.ClaudeOAuth.RefreshToken,
		"CLAUDE_OAUTH_CLIENT_ID":           spec.ClaudeOAuth.ClientID,
		"CLAUDE_OAUTH_SCOPES":              strings.Join(spec.ClaudeOAuth.Scopes, ","),
		"CLAUDE_OAUTH_TOKEN_URL":           spec.ClaudeOAuth.TokenURL,
	}
	for key, value := range spec.EnvOverrides {
		env[key] = value
	}

	if _, err := config.LoadFromMap(env); err != nil {
		return nil, fmt.Errorf("validate generated env: %w", err)
	}

	keys := []string{
		"PROXY_LISTEN_ADDR",
		"PROXY_LISTEN_PORT",
		"ADMIN_LISTEN_ADDR",
		"ADMIN_LISTEN_PORT",
		"PROXY_TLS_ENABLED",
		"PROXY_TLS_CERT_FILE",
		"PROXY_TLS_KEY_FILE",
		"AUTH_USERS_FILE",
		"AUTH_USERS",
		"SOURCE_ALLOWLIST_CIDRS",
		"DEST_PORT_ALLOWLIST",
		"DEST_HOST_ALLOWLIST",
		"DEST_SUFFIX_ALLOWLIST",
		"ALLOW_EMPTY_DEST_ALLOWLIST",
		"ALLOW_PRIVATE_DESTINATIONS",
		"MAX_CONNS_PER_IP",
		"SERVER_READ_HEADER_TIMEOUT",
		"SERVER_IDLE_TIMEOUT",
		"UPSTREAM_DIAL_TIMEOUT",
		"UPSTREAM_TLS_HANDSHAKE_TIMEOUT",
		"UPSTREAM_RESPONSE_HEADER_TIMEOUT",
		"TUNNEL_IDLE_TIMEOUT",
		"MAX_HEADER_BYTES",
		"LOG_LEVEL",
		"LOG_FORMAT",
		"ACCESS_LOG_ENABLED",
		"METRICS_ENABLED",
		"ALLOW_PUBLIC_ADMIN",
		"ALLOW_INSECURE_PUBLIC_PROXY",
		"CLAUDE_OAUTH_ENABLED",
		"CLAUDE_OAUTH_REFRESH_TOKEN",
		"CLAUDE_OAUTH_CLIENT_ID",
		"CLAUDE_OAUTH_SCOPES",
		"CLAUDE_OAUTH_TOKEN_URL",
	}
	extraKeys := make([]string, 0, len(env))
	for key := range env {
		if !contains(keys, key) {
			extraKeys = append(extraKeys, key)
		}
	}
	sort.Strings(extraKeys)
	keys = append(keys, extraKeys...)

	var builder strings.Builder
	builder.WriteString("# Generated by codex-gateway deploy vps\n")
	for _, key := range keys {
		builder.WriteString(key)
		builder.WriteString("=")
		builder.WriteString(env[key])
		builder.WriteString("\n")
	}
	return []byte(builder.String()), nil
}

func RenderVPSUsers(spec VPSConfig) ([]byte, error) {
	var builder strings.Builder
	builder.WriteString("# Generated by codex-gateway deploy vps\n")
	for _, user := range spec.Users {
		hash := strings.TrimSpace(user.BcryptHash)
		if hash == "" {
			generated, err := auth.HashPassword(user.Password, 12)
			if err != nil {
				return nil, fmt.Errorf("hash password for %s: %w", user.Username, err)
			}
			hash = generated
		}
		builder.WriteString(user.Username)
		builder.WriteString(":")
		builder.WriteString(hash)
		builder.WriteString("\n")
	}
	return []byte(builder.String()), nil
}

func RenderVPSService(spec VPSConfig) []byte {
	envPath := filepath.Join(spec.ProjectRoot, ".env")
	wantedBy := "default.target"
	if spec.ServiceScope == ServiceScopeSystem {
		wantedBy = "multi-user.target"
	}
	return []byte(fmt.Sprintf(`[Unit]
Description=Codex Gateway explicit proxy
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=%s
Environment=CODEX_GATEWAY_ENV_FILE=%s
EnvironmentFile=%s
ExecStart=%s
Restart=always
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=%s
`, spec.ProjectRoot, envPath, envPath, spec.BinaryOutput, wantedBy))
}

func RenderClientEnv(spec ClientConfig) []byte {
	return RenderClientEnvForEndpoint(spec.Proxy, primaryClientEndpoint(spec))
}

func RenderClientEnvForEndpoint(proxy ClientProxy, endpoint ClientEndpoint) []byte {
	proxyURL := fmt.Sprintf("http://%s:%s@%s:%d", proxy.Username, proxy.Password, endpoint.Tunnel.LocalHost, endpoint.Tunnel.LocalPort)
	noProxy := strings.Join(proxy.NoProxy, ",")

	var builder strings.Builder
	builder.WriteString("# Generated by codex-gateway deploy client\n")
	builder.WriteString("export HTTP_PROXY=" + shellQuote(proxyURL) + "\n")
	builder.WriteString("export HTTPS_PROXY=" + shellQuote(proxyURL) + "\n")
	builder.WriteString("export ALL_PROXY=" + shellQuote(proxyURL) + "\n")
	builder.WriteString("export NO_PROXY=" + shellQuote(noProxy) + "\n")
	return []byte(builder.String())
}

func RenderClaudeClientEnv(spec ClientConfig) []byte {
	var builder strings.Builder
	builder.WriteString("# Generated by codex-gateway deploy client\n")
	builder.WriteString("export ANTHROPIC_BASE_URL=" + shellQuote(fmt.Sprintf("http://%s:%d", spec.ClaudeCode.ListenHost, spec.ClaudeCode.ListenPort)) + "\n")
	builder.WriteString("export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC='1'\n")
	builder.WriteString("export CLAUDE_CODE_OAUTH_TOKEN='gateway-managed'\n")
	return []byte(builder.String())
}

func RenderClientWrapper(spec ClientConfig, envPath string) []byte {
	primary := primaryClientEndpoint(spec)
	return renderClientWrapper(spec.WrapperName, []clientWrapperEndpoint{{
		Name:      primary.Name,
		EnvPath:   envPath,
		LocalHost: primary.Tunnel.LocalHost,
		LocalPort: primary.Tunnel.LocalPort,
	}})
}

func RenderClientWrapperForEndpoints(spec ClientConfig, endpoints []clientWrapperEndpoint) []byte {
	return renderClientWrapper(spec.WrapperName, endpoints)
}

func RenderClaudeClientWrapper(spec ClientConfig, envPath string) []byte {
	return renderClientWrapper(spec.ClaudeCode.WrapperName, []clientWrapperEndpoint{{
		Name:      "primary",
		EnvPath:   envPath,
		LocalHost: spec.ClaudeCode.ListenHost,
		LocalPort: spec.ClaudeCode.ListenPort,
	}})
}

func renderClientWrapper(wrapperName string, endpoints []clientWrapperEndpoint) []byte {
	usage := fmt.Sprintf("usage: %s [--endpoint name] <command> [args...]", wrapperName)
	if len(endpoints) == 0 {
		return []byte(fmt.Sprintf(`#!/usr/bin/env sh
set -eu
if [ "$#" -eq 0 ]; then
  printf '%s\n' >&2
  exit 1
fi
exec "$@"
`, usage))
	}

	var builder strings.Builder
	builder.WriteString("#!/usr/bin/env sh\n")
	builder.WriteString("set -eu\n")
	builder.WriteString("selected_endpoint=${CODEX_GATEWAY_ENDPOINT:-}\n")
	builder.WriteString("if [ \"${1:-}\" = \"--endpoint\" ]; then\n")
	builder.WriteString("  if [ \"$#\" -lt 2 ]; then\n")
	builder.WriteString("    printf " + shellQuote(usage+"\\n") + " >&2\n")
	builder.WriteString("    exit 1\n")
	builder.WriteString("  fi\n")
	builder.WriteString("  selected_endpoint=$2\n")
	builder.WriteString("  shift 2\n")
	builder.WriteString("fi\n")
	builder.WriteString("if [ \"$#\" -eq 0 ]; then\n")
	builder.WriteString("  printf " + shellQuote(usage+"\\n") + " >&2\n")
	builder.WriteString("  exit 1\n")
	builder.WriteString("fi\n")
	builder.WriteString("select_endpoint() {\n")
	builder.WriteString("  case \"$1\" in\n")
	for _, endpoint := range endpoints {
		builder.WriteString("    " + shellQuote(endpoint.Name) + ")\n")
		builder.WriteString("      selected_name=" + shellQuote(endpoint.Name) + "\n")
		builder.WriteString("      env_path=" + shellQuote(endpoint.EnvPath) + "\n")
		builder.WriteString("      return 0\n")
		builder.WriteString("      ;;\n")
	}
	builder.WriteString("  esac\n")
	builder.WriteString("  return 1\n")
	builder.WriteString("}\n")
	builder.WriteString("pick_endpoint() {\n")
	builder.WriteString("  if command -v nc >/dev/null 2>&1; then\n")
	for _, endpoint := range endpoints {
		builder.WriteString("    if nc -z " + shellQuote(endpoint.LocalHost) + " " + shellQuote(strconv.Itoa(endpoint.LocalPort)) + " >/dev/null 2>&1; then\n")
		builder.WriteString("      select_endpoint " + shellQuote(endpoint.Name) + "\n")
		builder.WriteString("      return 0\n")
		builder.WriteString("    fi\n")
	}
	builder.WriteString("  fi\n")
	builder.WriteString("  select_endpoint " + shellQuote(endpoints[0].Name) + "\n")
	builder.WriteString("}\n")
	builder.WriteString("if [ -n \"$selected_endpoint\" ]; then\n")
	builder.WriteString("  if ! select_endpoint \"$selected_endpoint\"; then\n")
	builder.WriteString("    printf 'unknown endpoint: %s\\n' \"$selected_endpoint\" >&2\n")
	builder.WriteString("    exit 1\n")
	builder.WriteString("  fi\n")
	builder.WriteString("else\n")
	builder.WriteString("  pick_endpoint\n")
	builder.WriteString("fi\n")
	builder.WriteString("export CODEX_GATEWAY_ACTIVE_ENDPOINT=$selected_name\n")
	builder.WriteString(". \"$env_path\"\n")
	builder.WriteString("exec \"$@\"\n")
	return []byte(builder.String())
}

func RenderClientService(spec ClientConfig) []byte {
	return RenderClientServiceForEndpoint(spec, primaryClientEndpoint(spec))
}

func RenderClientServiceForEndpoint(spec ClientConfig, endpoint ClientEndpoint) []byte {
	description := "SSH tunnel to Codex Gateway"
	if isMultiEndpointClient(spec) {
		description = fmt.Sprintf("SSH tunnel to Codex Gateway (%s)", endpoint.Name)
	}
	return renderTunnelService(spec.ServiceScope, endpoint, endpoint.Tunnel, description)
}

func RenderClaudeAdminService(spec ClientConfig, endpoint ClientEndpoint) []byte {
	description := "SSH admin tunnel to Codex Gateway"
	adminTunnel := ClientTunnel{
		LocalHost:  spec.ClaudeCode.AdminLocalHost,
		LocalPort:  spec.ClaudeCode.AdminLocalPort,
		RemoteHost: spec.ClaudeCode.AdminRemoteHost,
		RemotePort: spec.ClaudeCode.AdminRemotePort,
	}
	return renderTunnelService(spec.ServiceScope, endpoint, adminTunnel, description)
}

func renderTunnelService(scope string, endpoint ClientEndpoint, tunnel ClientTunnel, description string) []byte {
	sshArgs := []string{
		"/usr/bin/ssh",
		"-N",
		"-L",
		fmt.Sprintf("%s:%d:%s:%d", tunnel.LocalHost, tunnel.LocalPort, tunnel.RemoteHost, tunnel.RemotePort),
		"-o",
		"ExitOnForwardFailure=yes",
		"-o",
		fmt.Sprintf("ServerAliveInterval=%d", endpoint.SSH.ServerAliveInterval),
		"-o",
		fmt.Sprintf("ServerAliveCountMax=%d", endpoint.SSH.ServerAliveCountMax),
	}
	if endpoint.SSH.Port != 22 {
		sshArgs = append(sshArgs, "-p", strconv.Itoa(endpoint.SSH.Port))
	}
	if endpoint.SSH.IdentityFile != "" {
		sshArgs = append(sshArgs, "-i", endpoint.SSH.IdentityFile)
	}
	sshArgs = append(sshArgs, endpoint.SSH.ExtraArgs...)
	sshArgs = append(sshArgs, fmt.Sprintf("%s@%s", endpoint.SSH.User, endpoint.SSH.Host))
	wantedBy := "default.target"
	if scope == ServiceScopeSystem {
		wantedBy = "multi-user.target"
	}

	return []byte(fmt.Sprintf(`[Unit]
Description=%s
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=%s
Restart=always
RestartSec=5

[Install]
WantedBy=%s
`, description, strings.Join(quoteSystemdArgs(sshArgs), " "), wantedBy))
}

func RenderClaudeClientConfig(spec ClientConfig, endpoint ClientEndpoint) ([]byte, error) {
	payload := map[string]any{
		"listen_addr":              net.JoinHostPort(spec.ClaudeCode.ListenHost, strconv.Itoa(spec.ClaudeCode.ListenPort)),
		"upstream_url":             spec.ClaudeCode.UpstreamURL,
		"proxy_url":                fmt.Sprintf("http://%s:%s@%s:%d", spec.Proxy.Username, spec.Proxy.Password, endpoint.Tunnel.LocalHost, endpoint.Tunnel.LocalPort),
		"oauth_broker_url":         fmt.Sprintf("http://%s:%d/claude/oauth/token", spec.ClaudeCode.AdminLocalHost, spec.ClaudeCode.AdminLocalPort),
		"oauth_username":           spec.Proxy.Username,
		"oauth_password":           spec.Proxy.Password,
		"tls_insecure_skip_verify": spec.ClaudeCode.TLSInsecureSkipVerify,
		"log_level":                "info",
		"log_format":               "json",
		"identity": map[string]any{
			"device_id": spec.ClaudeCode.Identity.DeviceID,
			"email":     spec.ClaudeCode.Identity.Email,
		},
		"env": map[string]any{
			"platform":               spec.ClaudeCode.Env.Platform,
			"platform_raw":           spec.ClaudeCode.Env.PlatformRaw,
			"arch":                   spec.ClaudeCode.Env.Arch,
			"node_version":           spec.ClaudeCode.Env.NodeVersion,
			"terminal":               spec.ClaudeCode.Env.Terminal,
			"package_managers":       spec.ClaudeCode.Env.PackageManagers,
			"runtimes":               spec.ClaudeCode.Env.Runtimes,
			"is_running_with_bun":    spec.ClaudeCode.Env.IsRunningWithBun,
			"is_claude_ai_auth":      spec.ClaudeCode.Env.IsClaudeAIAuth,
			"version":                spec.ClaudeCode.Env.Version,
			"version_base":           spec.ClaudeCode.Env.VersionBase,
			"build_time":             spec.ClaudeCode.Env.BuildTime,
			"deployment_environment": spec.ClaudeCode.Env.DeploymentEnvironment,
			"vcs":                    spec.ClaudeCode.Env.VCS,
		},
		"prompt_env": map[string]any{
			"platform":    spec.ClaudeCode.PromptEnv.Platform,
			"shell":       spec.ClaudeCode.PromptEnv.Shell,
			"os_version":  spec.ClaudeCode.PromptEnv.OSVersion,
			"working_dir": spec.ClaudeCode.PromptEnv.WorkingDir,
		},
		"process": map[string]any{
			"constrained_memory": spec.ClaudeCode.Process.ConstrainedMemory,
			"rss_range":          spec.ClaudeCode.Process.RSSRange,
			"heap_total_range":   spec.ClaudeCode.Process.HeapTotalRange,
			"heap_used_range":    spec.ClaudeCode.Process.HeapUsedRange,
		},
	}
	content, err := yaml.Marshal(payload)
	if err != nil {
		return nil, err
	}
	return content, nil
}

func RenderClaudeClientService(spec ClientConfig, configPath, proxyServiceName, adminServiceName string) []byte {
	wantedBy := "default.target"
	if spec.ServiceScope == ServiceScopeSystem {
		wantedBy = "multi-user.target"
	}
	var builder strings.Builder
	builder.WriteString("[Unit]\n")
	builder.WriteString("Description=Codex Gateway Claude rewrite client\n")
	builder.WriteString("After=network-online.target " + proxyServiceName + ".service " + adminServiceName + ".service\n")
	builder.WriteString("Wants=network-online.target " + proxyServiceName + ".service " + adminServiceName + ".service\n\n")
	builder.WriteString("[Service]\n")
	builder.WriteString("Type=simple\n")
	builder.WriteString("ExecStart=" + strings.Join(quoteSystemdArgs([]string{spec.ClaudeCode.BinaryOutput, "claude-client", "-config", configPath}), " ") + "\n")
	builder.WriteString("Restart=always\n")
	builder.WriteString("RestartSec=5\n\n")
	builder.WriteString("[Install]\n")
	builder.WriteString("WantedBy=" + wantedBy + "\n")
	return []byte(builder.String())
}

func joinInts(values []int) string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, strconv.Itoa(value))
	}
	return strings.Join(out, ",")
}

func contains(values []string, target string) bool {
	for _, value := range values {
		if value == target {
			return true
		}
	}
	return false
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'"'"'`) + "'"
}

func quoteSystemdArgs(values []string) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		if value == "" {
			out = append(out, `""`)
			continue
		}
		if strings.ContainsAny(value, " \t\"") {
			escaped := strings.ReplaceAll(value, `\`, `\\`)
			escaped = strings.ReplaceAll(escaped, `"`, `\"`)
			out = append(out, `"`+escaped+`"`)
			continue
		}
		out = append(out, value)
	}
	return out
}

func primaryClientEndpoint(spec ClientConfig) ClientEndpoint {
	if len(spec.Endpoints) > 0 {
		return spec.Endpoints[0]
	}
	return ClientEndpoint{
		Name:   "primary",
		SSH:    spec.SSH,
		Tunnel: spec.Tunnel,
	}
}

func clientEndpoints(spec ClientConfig) []ClientEndpoint {
	if len(spec.Endpoints) > 0 {
		cloned := make([]ClientEndpoint, len(spec.Endpoints))
		copy(cloned, spec.Endpoints)
		return cloned
	}
	return []ClientEndpoint{primaryClientEndpoint(spec)}
}

func isMultiEndpointClient(spec ClientConfig) bool {
	return len(clientEndpoints(spec)) > 1
}

func clientServiceName(spec ClientConfig, endpoint ClientEndpoint) string {
	if !isMultiEndpointClient(spec) {
		return spec.ServiceName
	}
	return spec.ServiceName + "-" + endpoint.Name
}
